"use client"

import { Order } from '@/types';
import { format } from 'date-fns';

export function Receipt({ order }: { order: Order }) {
  return (
    <div id="printable-receipt" className="text-black font-mono p-4">
      <div className="text-center mb-4">
        <h1 className="text-xl font-black uppercase">JP Food and Tandoori</h1>
        <p className="text-xs">Chaksibari, Thamel, Kathmandu</p>
        <p className="text-xs">Phone: +977-9800000000</p>
      </div>

      <div className="border-t border-b border-black py-2 my-2 text-sm">
        <div className="flex justify-between">
          <span>Table: {order.tableNumber}</span>
          <span>Order #: {order.id.slice(-5).toUpperCase()}</span>
        </div>
        <div className="flex justify-between">
          <span>Date: {format(order.createdAt, 'dd/MM/yyyy')}</span>
          <span>Time: {format(order.createdAt, 'hh:mm a')}</span>
        </div>
      </div>

      <table className="w-full text-sm mb-4">
        <thead>
          <tr className="border-b border-black">
            <th className="text-left py-1">Item</th>
            <th className="text-center py-1">Qty</th>
            <th className="text-right py-1">Price</th>
          </tr>
        </thead>
        <tbody>
          {order.items.map((item, idx) => (
            <tr key={idx}>
              <td className="py-1">{item.name}</td>
              <td className="text-center py-1">{item.qty}</td>
              <td className="text-right py-1">Rs. {item.price * item.qty}</td>
            </tr>
          ))}
        </tbody>
      </table>

      <div className="border-t border-black pt-2 space-y-1">
        <div className="flex justify-between font-bold text-lg">
          <span>Total</span>
          <span>Rs. {order.total}</span>
        </div>
        {order.paymentMethod && (
          <div className="flex justify-between text-sm uppercase">
            <span>Payment Method</span>
            <span>{order.paymentMethod}</span>
          </div>
        )}
      </div>

      <div className="text-center mt-8 text-xs border-t border-black pt-4">
        <p>Thank you for visiting!</p>
        <p>Visit us again soon.</p>
        <p className="mt-2 opacity-50 italic">Generated by JP Cafe POS</p>
      </div>
    </div>
  );
}
